import 'package:flame/components.dart';
import '../components/actors/arrow_tower.dart';
import '../components/objects/background_texture.dart';
import '../components/actors/water_enemy.dart';
import '../components/objects/ground_block.dart';
import '../components/objects/platform_block.dart';
import '../components/objects/star.dart';
import '../components/projectiles/arrow.dart';

class Block {
  final List<Vector2> gridPositions;
  final Type blockType;
  final String textureName;
  Block(this.gridPositions, this.blockType, {this.textureName = '203.jpg'});
}

final segments = [
  segment_1,
  // segment_1,
  // segment_1,
];

final segment_1 = [
  Block([Vector2(2, 2)], Arrow),
  Block([Vector2(1, 8)], ArrowTower),
  Block([Vector2(19, 8)], ArrowTower),
  Block([Vector2(4, 4), Vector2(16, 16)], BackgroundTexture,
      textureName: '209.jpg'),
];

final segment0 = [
  Block([Vector2(0, 0)], GroundBlock),
  Block([Vector2(0, 3)], PlatformBlock),
  Block([Vector2(1, 3)], PlatformBlock),
  Block([Vector2(2, 3)], PlatformBlock),
  Block([Vector2(1, 0)], GroundBlock),
  Block([Vector2(2, 0)], GroundBlock),
  Block([Vector2(3, 0)], GroundBlock),
  Block([Vector2(4, 0)], GroundBlock),
  Block([Vector2(5, 0)], GroundBlock),
  Block([Vector2(5, 1)], WaterEnemy),
  Block([Vector2(5, 3)], PlatformBlock),
  Block([Vector2(6, 0)], GroundBlock),
  Block([Vector2(6, 3)], PlatformBlock),
  Block([Vector2(7, 0)], GroundBlock),
  Block([Vector2(7, 3)], PlatformBlock),
  Block([Vector2(8, 0)], GroundBlock),
  Block([Vector2(8, 3)], PlatformBlock),
  Block([Vector2(9, 0)], GroundBlock),
];
final segment1 = [
  Block([Vector2(0, 0)], GroundBlock),
  Block([Vector2(1, 0)], GroundBlock),
  Block([Vector2(1, 1)], PlatformBlock),
  Block([Vector2(1, 2)], PlatformBlock),
  Block([Vector2(1, 3)], PlatformBlock),
  Block([Vector2(2, 6)], PlatformBlock),
  Block([Vector2(3, 6)], PlatformBlock),
  Block([Vector2(6, 5)], PlatformBlock),
  Block([Vector2(7, 5)], PlatformBlock),
  Block([Vector2(7, 7)], Star),
  Block([Vector2(8, 0)], GroundBlock),
  Block([Vector2(8, 1)], PlatformBlock),
  Block([Vector2(8, 5)], PlatformBlock),
  Block([Vector2(8, 6)], WaterEnemy),
  Block([Vector2(9, 0)], GroundBlock),
];
final segment2 = [
  Block([Vector2(0, 0)], GroundBlock),
  Block([Vector2(1, 0)], GroundBlock),
  Block([Vector2(2, 0)], GroundBlock),
  Block([Vector2(3, 0)], GroundBlock),
  Block([Vector2(3, 3)], PlatformBlock),
  Block([Vector2(4, 0)], GroundBlock),
  Block([Vector2(4, 3)], PlatformBlock),
  Block([Vector2(5, 0)], GroundBlock),
  Block([Vector2(5, 3)], PlatformBlock),
  Block([Vector2(5, 4)], WaterEnemy),
  Block([Vector2(6, 0)], GroundBlock),
  Block([Vector2(6, 3)], PlatformBlock),
  Block([Vector2(6, 4)], PlatformBlock),
  Block([Vector2(6, 5)], PlatformBlock),
  Block([Vector2(6, 7)], Star),
  Block([Vector2(7, 0)], GroundBlock),
  Block([Vector2(8, 0)], GroundBlock),
  Block([Vector2(9, 0)], GroundBlock),
];
final segment3 = [
  Block([Vector2(0, 0)], GroundBlock),
  Block([Vector2(1, 0)], GroundBlock),
  Block([Vector2(1, 1)], WaterEnemy),
  Block([Vector2(2, 0)], GroundBlock),
  Block([Vector2(2, 1)], PlatformBlock),
  Block([Vector2(2, 2)], PlatformBlock),
  Block([Vector2(4, 4)], PlatformBlock),
  Block([Vector2(6, 6)], PlatformBlock),
  Block([Vector2(7, 0)], GroundBlock),
  Block([Vector2(7, 1)], PlatformBlock),
  Block([Vector2(8, 0)], GroundBlock),
  Block([Vector2(8, 8)], Star),
  Block([Vector2(9, 0)], GroundBlock),
];
final segment4 = [
  Block([Vector2(0, 0)], GroundBlock),
  Block([Vector2(1, 0)], GroundBlock),
  Block([Vector2(2, 0)], GroundBlock),
  Block([Vector2(2, 3)], PlatformBlock),
  Block([Vector2(3, 0)], GroundBlock),
  Block([Vector2(3, 1)], WaterEnemy),
  Block([Vector2(3, 3)], PlatformBlock),
  Block([Vector2(4, 0)], GroundBlock),
  Block([Vector2(5, 0)], GroundBlock),
  Block([Vector2(5, 5)], PlatformBlock),
  Block([Vector2(5, 0)], GroundBlock),
  Block([Vector2(5, 5)], PlatformBlock),
  Block([Vector2(5, 7)], Star),
  Block([Vector2(7, 0)], GroundBlock),
  Block([Vector2(8, 0)], GroundBlock),
  Block([Vector2(8, 3)], PlatformBlock),
  Block([Vector2(9, 0)], GroundBlock),
  Block([Vector2(9, 1)], WaterEnemy),
  Block([Vector2(9, 3)], PlatformBlock),
];

final segment_0 = [
  Block([
    Vector2(0, 0),
    Vector2(0, 1),
    Vector2(0, 2),
    Vector2(0, 3),
    Vector2(0, 4),
    Vector2(0, 5),
    Vector2(0, 6),
    Vector2(0, 7),
    Vector2(0, 8),
    Vector2(0, 9),
    Vector2(1, 0),
    Vector2(1, 1),
    Vector2(1, 2),
    Vector2(1, 3),
    Vector2(1, 4),
    Vector2(1, 5),
    Vector2(1, 6),
    Vector2(1, 7),
    Vector2(1, 8),
    Vector2(1, 9),
    Vector2(2, 0),
    Vector2(2, 1),
    Vector2(2, 2),
    Vector2(2, 3),
    Vector2(2, 4),
    Vector2(2, 5),
    Vector2(2, 6),
    Vector2(2, 7),
    Vector2(2, 8),
    Vector2(2, 9),
    Vector2(3, 0),
    Vector2(3, 1),
    Vector2(3, 2),
    Vector2(3, 3),
    Vector2(3, 4),
    Vector2(3, 5),
    Vector2(3, 6),
    Vector2(3, 7),
    Vector2(3, 8),
    Vector2(3, 9),
    Vector2(4, 0),
    Vector2(4, 1),
    Vector2(4, 2),
    Vector2(4, 3),
    Vector2(4, 4),
    Vector2(4, 5),
    Vector2(4, 6),
    Vector2(4, 7),
    Vector2(4, 8),
    Vector2(4, 9),
    Vector2(5, 0),
    Vector2(5, 1),
    Vector2(5, 2),
    Vector2(5, 3),
    Vector2(5, 4),
    Vector2(5, 5),
    Vector2(5, 6),
    Vector2(5, 7),
    Vector2(5, 8),
    Vector2(5, 9),
    Vector2(6, 0),
    Vector2(6, 1),
    Vector2(6, 2),
    Vector2(6, 3),
    Vector2(6, 4),
    Vector2(6, 5),
    Vector2(6, 6),
    Vector2(6, 7),
    Vector2(6, 8),
    Vector2(6, 9),
    Vector2(7, 0),
    Vector2(7, 1),
    Vector2(7, 2),
    Vector2(7, 3),
    Vector2(7, 4),
    Vector2(7, 5),
    Vector2(7, 6),
    Vector2(7, 7),
    Vector2(7, 8),
    Vector2(7, 9),
    Vector2(8, 0),
    Vector2(8, 1),
    Vector2(8, 2),
    Vector2(8, 3),
    Vector2(8, 4),
    Vector2(8, 5),
    Vector2(8, 6),
    Vector2(8, 7),
    Vector2(8, 8),
    Vector2(8, 9),
    Vector2(9, 0),
    Vector2(9, 1),
    Vector2(9, 2),
    Vector2(9, 3),
    Vector2(9, 4),
    Vector2(9, 5),
    Vector2(9, 6),
    Vector2(9, 7),
    Vector2(9, 8),
    Vector2(9, 9),
  ], BackgroundTexture, textureName: '209.jpg'),
  // Block([Vector2(0, 1)], BackgroundTexture, textureName: '203.jpg'),
];
