name: tower_defense
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^2.17.0
  flutter: ^2.10.0

dependencies:
  flame: ^1.7.3
  flutter:
    sdk: flutter

flutter:
  assets:
  - assets/images/
dev_dependencies:
  flutter_lints: ^2.0.1

